"""The single-arm Franka FR3 robot's bundled description.

A standalone FR3 — one arm, fixed base, no extrinsic — that mirrors
the *shape* of :mod:`bimanual_franka_planning.bimanual_franka` so the
Python factories (``create_planner``, ``create_ik_solver``) can pick
one or the other purely by name.

State vector layout (7 DOF total):

    [0:7]    fr3 arm    (fr3_joint1..7)

The single-arm URDF lives in
``resources/robot/single_fr3/single_fr3.urdf`` and ships its own
copy of the FR3 meshes (collision STLs + visual DAEs) so it stays
self-contained — no symlinks back into the bimanual tree.

Motion planning uses the dedicated
``vamp::robots::SingleFr3`` FK header generated by cricket from
``single_fr3_spherized.urdf`` — the OMPL+VAMP C++ extension exposes
it as ``_ompl_vamp.SingleFr3OmplVampPlanner``, in parallel with
``OmplVampPlanner`` for the bimanual cell.

There are no subgroups: a single arm is already its own smallest
planning unit.  The empty ``PLANNING_SUBGROUPS`` dict keeps the
registry interface uniform with the bimanual description.
"""

from __future__ import annotations

import os

import numpy as np

from bimanual_franka_planning.types.robot import (
    CameraConfig,
    ChainConfig,
    RobotConfig,
)

_PKG_ROOT = os.path.dirname(os.path.abspath(__file__))
_RESOURCES_DIR = os.path.join(_PKG_ROOT, "resources", "robot", "single_fr3")

# Atomic joint group — index slice into the full 7-DOF configuration.
JOINT_GROUPS = {
    "arm": slice(0, 7),
}

CHAIN_CONFIGS: dict[str, ChainConfig] = {
    "single_fr3": ChainConfig(
        base_link="fr3_link0",
        ee_link="fr3_link8",
        num_joints=7,
        urdf_path=os.path.join(_RESOURCES_DIR, "single_fr3.urdf"),
    ),
}

VIZ_URDF_PATH = os.path.join(_RESOURCES_DIR, "single_fr3.urdf")

# Per-joint TOTG limits — same FR3 datasheet numbers each arm uses
# in the bimanual config, just without the relative-base prefix.
MAX_VELOCITY = np.array([2.62, 2.62, 2.62, 2.62, 5.26, 4.18, 5.26])
MAX_ACCELERATION = np.full(7, 6.0)

single_fr3_robot_config = RobotConfig(
    urdf_path=os.path.join(_RESOURCES_DIR, "single_fr3.urdf"),
    joint_names=[
        "fr3_joint1",
        "fr3_joint2",
        "fr3_joint3",
        "fr3_joint4",
        "fr3_joint5",
        "fr3_joint6",
        "fr3_joint7",
    ],
    camera=CameraConfig(
        link_name="fr3_link0",
        width=640,
        height=480,
        fov=60.0,
        near=0.1,
        far=10.0,
    ),
    max_velocity=MAX_VELOCITY,
    max_acceleration=MAX_ACCELERATION,
)

# A single arm has no meaningful sub-group — the arm itself is the
# only thing one would plan over.  Keeping the empty dict in place
# means the registry can iterate over every description's
# ``PLANNING_SUBGROUPS`` without special-casing single-arm robots.
PLANNING_SUBGROUPS: dict[str, dict] = {}

# Franka "ready" stance — same canonical neutral pose each arm in
# the bimanual config uses, lifted out of its 17-DOF embedding.
HOME_JOINTS = np.array([0.0, -0.785398, 0.0, -2.356194, 0.0, 1.570796, 0.785398])
